version: '3.8'

services:
  diet-analysis:
    image: diet-analysis
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    container_name: diet-analysis-container
